### ISSUE TITLE
Idea: specify language for all default attributes

### ISSUE THREAD

**Issue by philipp-maschke** [bpmn-miwg/bpmn-i18n#1]
The proposal should include some way to specify which language the default attributes represent. Otherwise importing tools will have to guess which language to map these values to.
Maybe as an attribute of the 'definitions' node or as an extension element to that node (not sure if that is allowed).

**Comment by falko** [comment]
Hi Philipp,

thank you for your suggestion. The i18n extension relies on the `xml:lang` attribute to declare the language. This attribute can also be used to set the language of an entire XML document, i.e. you can set `xml:lang` on the `bpmn:definitions` root element. So in other words, XML can already do this, even without the extension. `i18n:translation` elements can then deviate from the global language of the document by setting `xml:lang` locally.

Cheers,
Falko

**Comment by philipp-maschke** [comment]
Ah, thx that makes sense.
I would recommend to at least make this aspect part of the example or maybe even document it as a convention that should be followed.
What do you think?

**Comment by falko** [comment]
That's a good idea. Would you contribute that as a pull request?

**Comment by philipp-maschke** [comment]
Sure - I would propose to add it both to the example in the XSD and add a section to the readme, ok?

**Comment by falko** [comment]
Yes, that sounds good.

Since your tool supports different languages: Do you also have a small example that you could contribute?

**Comment by philipp-maschke** [comment]
I would love to, but we haven't implemented the extension yet. We currently still export only one selected language.

**Comment by falko** [comment]
Hm... I thought I saw some custom extension that allowed you to export translations. Anyway, if you have any good example in multiple languages that we manually equip with the i18n extensions, it might be a nice test case.

**Comment by philipp-maschke** [comment]
I'll do that once we implement the extension ;)
